services:
  dev:
    image: faceoffdev/php-fpm:${PHP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      target: php_nginx_dev
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_PREFIX=${PHP_PREFIX}
