name: Build and Push Node Docker Images

on:
  push:
    paths:
      - 'node/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  build-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node_version: ["lts-slim"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./node/
          file: ./node/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/node:${{ matrix.node_version }}
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
