name: Build and Push PHP Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Сначала собираем php-cli образы
  build-cli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        php_version: ["8.4", "8.4-dev"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract PHP_PREFIX
        run: |
          PHP_PREFIX=$(echo "${{ matrix.php_version }}" | grep -oE '[0-9]+\.[0-9]+' | tr -d '.')
          echo "PHP_PREFIX=$PHP_PREFIX" >> $GITHUB_ENV

      - name: Build and Push CLI Image
        uses: docker/build-push-action@v5
        with:
          context: ./php/cli/
          file: ./php/cli/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          target: php_cli${{ matrix.php_version == '8.4-dev' && '_dev' || '' }}
          tags: |
            ghcr.io/${{ github.repository }}/php-cli:${{ matrix.php_version }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_PREFIX=${{ env.PHP_PREFIX }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Потом fpm/cron, которые зависят от php-cli
  build-fpm-cron:
    needs: build-cli
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: php-fpm
            target: php_fpm
            php_version: "8.4"
            context: ./php/fpm/
            file: ./php/fpm/Dockerfile

          - name: php-cron
            target: php_cron
            php_version: "8.4"
            context: ./php/cron/
            file: ./php/cron/Dockerfile

          - name: php-fpm
            target: php_fpm_dev
            php_version: "8.4-dev"
            context: ./php/fpm/
            file: ./php/fpm/Dockerfile

          - name: php-cron
            target: php_cron_dev
            php_version: "8.4-dev"
            context: ./php/cron/
            file: ./php/cron/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract PHP_PREFIX
        run: |
          PHP_PREFIX=$(echo "${{ matrix.php_version }}" | grep -oE '[0-9]+\.[0-9]+' | tr -d '.')
          echo "PHP_PREFIX=$PHP_PREFIX" >> $GITHUB_ENV

      - name: Build and Push Dependent Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          target: ${{ matrix.target }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ matrix.php_version }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_PREFIX=${{ env.PHP_PREFIX }}
            PHP_CLI_IMAGE=ghcr.io/${{ github.repository }}/php-cli
          cache-from: type=gha
          cache-to: type=gha,mode=max
